const PDFDocument = require('pdfkit');
const { money } = require('./subscriptionInvoicePdf');

function displayTimestamp(value) {
  if (!value) return '-';
  return new Intl.DateTimeFormat('en-SG', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'Asia/Singapore',
    timeZoneName: 'short'
  }).format(new Date(value));
}

function generateSubscriptionPaymentReceiptPDF(invoice, payment) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 48,
    info: {
      Title: `Payment Receipt ${invoice.number}`,
      Author: 'Vaniday Singapore Pte. Ltd.',
      Subject: 'Partner Subscription Payment Receipt'
    }
  });
  const currency = payment.currency || invoice.currency || 'SGD';
  const refunded = payment.status === 'Refunded';

  doc.rect(0, 0, doc.page.width, 128).fill(refunded ? '#475569' : '#075f46');
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(21).text('VANIDAY SINGAPORE', 48, 38);
  doc.font('Helvetica').fontSize(9).text('Partner Subscription Billing', 48, 67);
  doc.font('Helvetica-Bold').fontSize(24).text('PAYMENT RECEIPT', 300, 35, { width: 247, align: 'right' });
  doc.font('Helvetica').fontSize(10).text(invoice.number, 300, 72, { width: 247, align: 'right' });

  const rows = [
    ['Customer', invoice.businessNameSnapshot],
    ['Invoice number', invoice.number],
    ['Subscription plan', invoice.planNameSnapshot],
    ['Payment provider', payment.provider],
    ['Payment status', payment.status],
    ['Paid at', displayTimestamp(payment.paidAt)],
    ['Provider reference', payment.providerReference],
    ['Amount received', money(payment.receivedAmount, currency)]
  ];
  let y = 165;
  rows.forEach(([label, value], index) => {
    if (index % 2 === 0) doc.rect(48, y - 7, 499, 31).fill('#f1f7f3');
    doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text(label.toUpperCase(), 60, y, { width: 170 });
    doc.fillColor('#102033').font('Helvetica').fontSize(10).text(String(value || '-'), 235, y, { width: 300, align: 'right' });
    y += 31;
  });

  if (refunded) {
    y += 18;
    doc.roundedRect(48, y, 499, 104, 8).fill('#f1f5f9');
    doc.fillColor('#334155').font('Helvetica-Bold').fontSize(12).text('REFUND RECORDED', 64, y + 17);
    doc.font('Helvetica').fontSize(9)
      .text(`Refunded at: ${displayTimestamp(payment.refundedAt)}`, 64, y + 42)
      .text(`Refund reference: ${payment.refundReference || '-'}`, 64, y + 59)
      .text(`Refund amount: ${money(payment.refundAmount, currency)}`, 320, y + 42)
      .text(`Reason: ${payment.refundReason || '-'}`, 64, y + 76, { width: 465 });
  }

  doc.moveTo(48, 748).lineTo(547, 748).strokeColor('#dbe5df').lineWidth(0.6).stroke();
  doc.fillColor('#64748b').font('Helvetica').fontSize(8)
    .text('This receipt records a Stripe sandbox transaction. No real money was transferred.', 48, 762)
    .text('Generated by the Partner Subscription Billing system.', 48, 778);
  doc.end();
  return doc;
}

module.exports = {
  displayTimestamp,
  generateSubscriptionPaymentReceiptPDF
};
