const PDFDocument = require('pdfkit');

function money(value, currency) {
  return `${currency} ${Number(value || 0).toFixed(2)}`;
}

function displayDate(value) {
  if (!value) return '-';
  return new Intl.DateTimeFormat('en-SG', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    timeZone: 'UTC'
  }).format(new Date(`${String(value).slice(0, 10)}T00:00:00.000Z`));
}

function drawLabelValue(doc, label, value, x, y, width) {
  doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text(label.toUpperCase(), x, y, { width });
  doc.fillColor('#102033').font('Helvetica').fontSize(10).text(String(value || '-'), x, y + 13, { width });
}

function generateSubscriptionInvoicePDF(invoice, items = []) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 48,
    info: {
      Title: `Subscription Invoice ${invoice.number}`,
      Author: 'Vaniday Singapore Pte. Ltd.',
      Subject: 'Monthly Partner Subscription Invoice'
    }
  });
  const currency = invoice.currency || 'SGD';
  const pageWidth = doc.page.width;
  const contentWidth = pageWidth - 96;

  doc.rect(0, 0, pageWidth, 122).fill('#075f46');
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(21).text('VANIDAY SINGAPORE', 48, 38);
  doc.font('Helvetica').fontSize(9).fillColor('#d1fae5').text('Partner Subscription Billing', 48, 66);
  doc.font('Helvetica-Bold').fontSize(26).fillColor('#ffffff').text('INVOICE', pageWidth - 220, 35, {
    width: 172,
    align: 'right'
  });
  doc.font('Helvetica').fontSize(10).fillColor('#d1fae5').text(invoice.number, pageWidth - 220, 70, {
    width: 172,
    align: 'right'
  });

  drawLabelValue(doc, 'Bill to', invoice.businessNameSnapshot, 48, 150, 235);
  drawLabelValue(doc, 'Billing email', invoice.billingEmailSnapshot, 48, 196, 235);
  drawLabelValue(doc, 'Invoice date', displayDate(invoice.invoiceDate), 335, 150, 105);
  drawLabelValue(doc, 'Due date', displayDate(invoice.dueDate), 450, 150, 105);
  drawLabelValue(
    doc,
    'Billing period',
    `${displayDate(invoice.billingPeriodStart)} – ${displayDate(invoice.billingPeriodEnd)}`,
    335,
    196,
    220
  );

  const tableTop = 262;
  doc.roundedRect(48, tableTop, contentWidth, 28, 4).fill('#e8f5ee');
  doc.fillColor('#075f46').font('Helvetica-Bold').fontSize(8)
    .text('DESCRIPTION', 60, tableTop + 10, { width: 265 })
    .text('QTY', 330, tableTop + 10, { width: 48, align: 'right' })
    .text('UNIT PRICE', 390, tableTop + 10, { width: 72, align: 'right' })
    .text('AMOUNT', 474, tableTop + 10, { width: 70, align: 'right' });

  let rowY = tableTop + 40;
  const rows = items.length ? items : [{
    description: invoice.description,
    quantity: 1,
    unitPrice: invoice.subtotal,
    lineAmount: invoice.subtotal
  }];
  rows.forEach((item) => {
    doc.fillColor('#102033').font('Helvetica').fontSize(9)
      .text(item.description, 60, rowY, { width: 265 })
      .text(Number(item.quantity).toFixed(2), 330, rowY, { width: 48, align: 'right' })
      .text(money(item.unitPrice, currency), 390, rowY, { width: 72, align: 'right' })
      .text(money(item.lineAmount, currency), 474, rowY, { width: 70, align: 'right' });
    rowY += 28;
    doc.moveTo(48, rowY - 8).lineTo(547, rowY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
  });

  const totalsY = Math.max(rowY + 18, 360);
  doc.fillColor('#64748b').font('Helvetica').fontSize(9)
    .text('Subtotal', 385, totalsY, { width: 78, align: 'right' })
    .text('Tax', 385, totalsY + 22, { width: 78, align: 'right' });
  doc.fillColor('#102033')
    .text(money(invoice.subtotal, currency), 474, totalsY, { width: 70, align: 'right' })
    .text(money(invoice.taxAmount, currency), 474, totalsY + 22, { width: 70, align: 'right' });
  doc.roundedRect(375, totalsY + 48, 178, 38, 5).fill('#075f46');
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(11)
    .text('TOTAL', 389, totalsY + 62)
    .text(money(invoice.totalAmount, currency), 454, totalsY + 62, { width: 84, align: 'right' });

  const features = Array.isArray(invoice.planFeaturesSnapshot) ? invoice.planFeaturesSnapshot : [];
  doc.fillColor('#102033').font('Helvetica-Bold').fontSize(10).text(
    `${invoice.planNameSnapshot} subscription`,
    48,
    totalsY + 118
  );
  doc.fillColor('#64748b').font('Helvetica').fontSize(8).text(
    features.length ? `Included: ${features.join(' • ')}` : 'Monthly partner subscription',
    48,
    totalsY + 135,
    { width: contentWidth }
  );

  doc.moveTo(48, 750).lineTo(547, 750).strokeColor('#dbe5df').lineWidth(0.6).stroke();
  doc.fillColor('#64748b').font('Helvetica').fontSize(8)
    .text(`Payment terms: Net ${Number(invoice.paymentTermsDaysSnapshot)} days`, 48, 762)
    .text('This document is generated by the Partner Subscription Billing system.', 48, 778);

  doc.end();
  return doc;
}

module.exports = {
  generateSubscriptionInvoicePDF,
  displayDate,
  money
};
